### ISSUE TITLE
About PS2 Version.

### ISSUE THREAD

**Issue by ghost** [ShadowTheHedgehogHacking/ShadowTHTextEditor#5]
Hello, congratulations on the tool, it is very useful to the translators/modders community. 
However, I have a doubt, will there be an implementation for the PlayStation 2 files? Thanks!

**Comment by dreamsyntax** [comment]
Hi, there are no plans as this is a different format. PS2 version of the game also performs the worst relative to other versions. PS2 version also has audio desync in event/cutscenes even in JPN audio.

There is no need to support it. I do believe another group cracked it at some point as there are unofficial PS2 translations floating around.
